# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m66d5LnJ-YuASAFbon-FlR7j1oTBxk5U
"""

a=int(input("Enter the cost of First Element:"))
b=int(input("Enter the cost of Second Element:"))
c=int(input("Enter the cost of Third Element:"))
d=a+b+c
e=d*10/100
if(d>50):
  f=d-e
  print("Total cost of three items",f)